[package]
name = "darkrouter-client-sdk"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "darkrouter_client"
path = "src/lib.rs"

[dependencies]
darkrouter-crypto = { path = "../darkrouter-crypto" }
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
rsa = { workspace = true }
num-bigint-dig = { version = "0.8", features = ["rand"] }
num-traits = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }
x25519-dalek = { workspace = true }
url = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
